import Head from "next/head";
import { Inter } from "@next/font/google";
import MyForm from "@/components/chatgpt-two";
import Calculator from "@/components/Calculator";
import Kubernetes from "@/components/services/kubernetes";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Civo Cost Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-500 min-h-screen">
        <h1 className="text-2xl p-2 text-center">Civo Cost Calculator</h1>
        <Calculator />
        {/* <ChatGpt /> */}
        {/* <MyForm/> */}
        {/* <Kubernetes /> */}
      </main>
    </>
  );
}
